site_name: Unijoysticle
site_url: https://retro.moe/
site_author: Ricardo Quesada
copyright: Copyright &copy; 2019-2024 Ricardo Quesada & contributors

repo_url: https://github.com/ricardoquesada/unijoysticle2
repo_name: ricardoquesada/unijoysticle2
edit_uri: blob/develop/docs

theme:
  name: material
  features:
    - navigation.expand
  font: false
  icon:
    repo: fontawesome/brands/github

nav:
  - Home: index.md
  - User Guide: user_guide.md

extra:
  analytics:
    provider: google
    property: G-8QS6NSDYEM

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - toc:
      permalink: true

plugins:
  - include-markdown
